name: "Setup dev environment"
description: "Setup Python development environment with uv"

inputs:
  uv-version:
    description: "Version of uv to install"
    required: false
    default: "0.8.17"

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6.7.0
      with:
        version: ${{ inputs.uv-version }}
        enable-cache: true
        cache-dependency-glob: uv.lock

    - name: Set up Python
      uses: actions/setup-python@v5.4.0
      with:
        python-version-file: pyproject.toml
