// auto-generated export definition header
#pragma once
#include <RDGeneral/RDExportMacros.h>

// RDKIT_ABBREVIATIONS_EXPORT definitions
#ifdef RDKIT_ABBREVIATIONS_BUILD
#define RDKIT_ABBREVIATIONS_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_ABBREVIATIONS_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_ABBREVIATIONS_EXPORT end definitions

// RDKIT_ALIGNMENT_EXPORT definitions
#ifdef RDKIT_ALIGNMENT_BUILD
#define RDKIT_ALIGNMENT_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_ALIGNMENT_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_ALIGNMENT_EXPORT end definitions

// RDKIT_AVALONLIB_EXPORT definitions
#ifdef RDKIT_AVALONLIB_BUILD
#define RDKIT_AVALONLIB_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_AVALONLIB_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_AVALONLIB_EXPORT end definitions

// RDKIT_CIPLABELER_EXPORT definitions
#ifdef RDKIT_CIPLABELER_BUILD
#define RDKIT_CIPLABELER_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_CIPLABELER_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_CIPLABELER_EXPORT end definitions

// RDKIT_CATALOGS_EXPORT definitions
#ifdef RDKIT_CATALOGS_BUILD
#define RDKIT_CATALOGS_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_CATALOGS_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_CATALOGS_EXPORT end definitions

// RDKIT_CHEMREACTIONS_EXPORT definitions
#ifdef RDKIT_CHEMREACTIONS_BUILD
#define RDKIT_CHEMREACTIONS_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_CHEMREACTIONS_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_CHEMREACTIONS_EXPORT end definitions

// RDKIT_CHEMTRANSFORMS_EXPORT definitions
#ifdef RDKIT_CHEMTRANSFORMS_BUILD
#define RDKIT_CHEMTRANSFORMS_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_CHEMTRANSFORMS_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_CHEMTRANSFORMS_EXPORT end definitions

// RDKIT_CHEMICALFEATURES_EXPORT definitions
#ifdef RDKIT_CHEMICALFEATURES_BUILD
#define RDKIT_CHEMICALFEATURES_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_CHEMICALFEATURES_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_CHEMICALFEATURES_EXPORT end definitions

// RDKIT_CONFORMERPARSER_EXPORT definitions
#ifdef RDKIT_CONFORMERPARSER_BUILD
#define RDKIT_CONFORMERPARSER_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_CONFORMERPARSER_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_CONFORMERPARSER_EXPORT end definitions

// RDKIT_DATASTRUCTS_EXPORT definitions
#ifdef RDKIT_DATASTRUCTS_BUILD
#define RDKIT_DATASTRUCTS_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_DATASTRUCTS_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_DATASTRUCTS_EXPORT end definitions

// RDKIT_DEPICTOR_EXPORT definitions
#ifdef RDKIT_DEPICTOR_BUILD
#define RDKIT_DEPICTOR_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_DEPICTOR_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_DEPICTOR_EXPORT end definitions

// RDKIT_DEPROTECT_EXPORT definitions
#ifdef RDKIT_DEPROTECT_BUILD
#define RDKIT_DEPROTECT_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_DEPROTECT_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_DEPROTECT_EXPORT end definitions

// RDKIT_DESCRIPTORS_EXPORT definitions
#ifdef RDKIT_DESCRIPTORS_BUILD
#define RDKIT_DESCRIPTORS_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_DESCRIPTORS_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_DESCRIPTORS_EXPORT end definitions

// RDKIT_DISTGEOMHELPERS_EXPORT definitions
#ifdef RDKIT_DISTGEOMHELPERS_BUILD
#define RDKIT_DISTGEOMHELPERS_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_DISTGEOMHELPERS_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_DISTGEOMHELPERS_EXPORT end definitions

// RDKIT_DISTGEOMETRY_EXPORT definitions
#ifdef RDKIT_DISTGEOMETRY_BUILD
#define RDKIT_DISTGEOMETRY_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_DISTGEOMETRY_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_DISTGEOMETRY_EXPORT end definitions

// RDKIT_EHTLIB_EXPORT definitions
#ifdef RDKIT_EHTLIB_BUILD
#define RDKIT_EHTLIB_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_EHTLIB_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_EHTLIB_EXPORT end definitions

// RDKIT_EIGENSOLVERS_EXPORT definitions
#ifdef RDKIT_EIGENSOLVERS_BUILD
#define RDKIT_EIGENSOLVERS_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_EIGENSOLVERS_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_EIGENSOLVERS_EXPORT end definitions

// RDKIT_FMCS_EXPORT definitions
#ifdef RDKIT_FMCS_BUILD
#define RDKIT_FMCS_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_FMCS_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_FMCS_EXPORT end definitions

// RDKIT_FILEPARSERS_EXPORT definitions
#ifdef RDKIT_FILEPARSERS_BUILD
#define RDKIT_FILEPARSERS_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_FILEPARSERS_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_FILEPARSERS_EXPORT end definitions

// RDKIT_FILTERCATALOG_EXPORT definitions
#ifdef RDKIT_FILTERCATALOG_BUILD
#define RDKIT_FILTERCATALOG_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_FILTERCATALOG_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_FILTERCATALOG_EXPORT end definitions

// RDKIT_FINGERPRINTS_EXPORT definitions
#ifdef RDKIT_FINGERPRINTS_BUILD
#define RDKIT_FINGERPRINTS_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_FINGERPRINTS_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_FINGERPRINTS_EXPORT end definitions

// RDKIT_FORCEFIELD_EXPORT definitions
#ifdef RDKIT_FORCEFIELD_BUILD
#define RDKIT_FORCEFIELD_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_FORCEFIELD_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_FORCEFIELD_EXPORT end definitions

// RDKIT_FORCEFIELDHELPERS_EXPORT definitions
#ifdef RDKIT_FORCEFIELDHELPERS_BUILD
#define RDKIT_FORCEFIELDHELPERS_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_FORCEFIELDHELPERS_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_FORCEFIELDHELPERS_EXPORT end definitions

// RDKIT_FRAGCATALOG_EXPORT definitions
#ifdef RDKIT_FRAGCATALOG_BUILD
#define RDKIT_FRAGCATALOG_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_FRAGCATALOG_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_FRAGCATALOG_EXPORT end definitions

// RDKIT_FREESASALIB_EXPORT definitions
#ifdef RDKIT_FREESASALIB_BUILD
#define RDKIT_FREESASALIB_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_FREESASALIB_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_FREESASALIB_EXPORT end definitions

// RDKIT_GRAPHMOL_EXPORT definitions
#ifdef RDKIT_GRAPHMOL_BUILD
#define RDKIT_GRAPHMOL_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_GRAPHMOL_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_GRAPHMOL_EXPORT end definitions

// RDKIT_INCHI_EXPORT definitions
#ifdef RDKIT_INCHI_BUILD
#define RDKIT_INCHI_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_INCHI_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_INCHI_EXPORT end definitions

// RDKIT_INFOTHEORY_EXPORT definitions
#ifdef RDKIT_INFOTHEORY_BUILD
#define RDKIT_INFOTHEORY_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_INFOTHEORY_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_INFOTHEORY_EXPORT end definitions

// RDKIT_MMPA_EXPORT definitions
#ifdef RDKIT_MMPA_BUILD
#define RDKIT_MMPA_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_MMPA_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_MMPA_EXPORT end definitions

// RDKIT_MOLALIGN_EXPORT definitions
#ifdef RDKIT_MOLALIGN_BUILD
#define RDKIT_MOLALIGN_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_MOLALIGN_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_MOLALIGN_EXPORT end definitions

// RDKIT_MOLCATALOG_EXPORT definitions
#ifdef RDKIT_MOLCATALOG_BUILD
#define RDKIT_MOLCATALOG_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_MOLCATALOG_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_MOLCATALOG_EXPORT end definitions

// RDKIT_MOLCHEMICALFEATURES_EXPORT definitions
#ifdef RDKIT_MOLCHEMICALFEATURES_BUILD
#define RDKIT_MOLCHEMICALFEATURES_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_MOLCHEMICALFEATURES_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_MOLCHEMICALFEATURES_EXPORT end definitions

// RDKIT_MOLDRAW2D_EXPORT definitions
#ifdef RDKIT_MOLDRAW2D_BUILD
#define RDKIT_MOLDRAW2D_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_MOLDRAW2D_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_MOLDRAW2D_EXPORT end definitions

// RDKIT_MOLDRAW2DQT_EXPORT definitions
#ifdef RDKIT_MOLDRAW2DQT_BUILD
#define RDKIT_MOLDRAW2DQT_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_MOLDRAW2DQT_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_MOLDRAW2DQT_EXPORT end definitions

// RDKIT_MOLENUMERATOR_EXPORT definitions
#ifdef RDKIT_MOLENUMERATOR_BUILD
#define RDKIT_MOLENUMERATOR_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_MOLENUMERATOR_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_MOLENUMERATOR_EXPORT end definitions

// RDKIT_MOLHASH_EXPORT definitions
#ifdef RDKIT_MOLHASH_BUILD
#define RDKIT_MOLHASH_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_MOLHASH_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_MOLHASH_EXPORT end definitions

// RDKIT_MOLINTERCHANGE_EXPORT definitions
#ifdef RDKIT_MOLINTERCHANGE_BUILD
#define RDKIT_MOLINTERCHANGE_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_MOLINTERCHANGE_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_MOLINTERCHANGE_EXPORT end definitions

// RDKIT_MOLSTANDARDIZE_EXPORT definitions
#ifdef RDKIT_MOLSTANDARDIZE_BUILD
#define RDKIT_MOLSTANDARDIZE_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_MOLSTANDARDIZE_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_MOLSTANDARDIZE_EXPORT end definitions

// RDKIT_MOLTRANSFORMS_EXPORT definitions
#ifdef RDKIT_MOLTRANSFORMS_BUILD
#define RDKIT_MOLTRANSFORMS_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_MOLTRANSFORMS_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_MOLTRANSFORMS_EXPORT end definitions

// RDKIT_O3AALIGN_EXPORT definitions
#ifdef RDKIT_O3AALIGN_BUILD
#define RDKIT_O3AALIGN_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_O3AALIGN_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_O3AALIGN_EXPORT end definitions

// RDKIT_OPTIMIZER_EXPORT definitions
#ifdef RDKIT_OPTIMIZER_BUILD
#define RDKIT_OPTIMIZER_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_OPTIMIZER_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_OPTIMIZER_EXPORT end definitions

// RDKIT_PARTIALCHARGES_EXPORT definitions
#ifdef RDKIT_PARTIALCHARGES_BUILD
#define RDKIT_PARTIALCHARGES_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_PARTIALCHARGES_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_PARTIALCHARGES_EXPORT end definitions

// RDKIT_RDBOOST_EXPORT definitions
#ifdef RDKIT_RDBOOST_BUILD
#define RDKIT_RDBOOST_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_RDBOOST_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_RDBOOST_EXPORT end definitions

// RDKIT_RDGENERAL_EXPORT definitions
#ifdef RDKIT_RDGENERAL_BUILD
#define RDKIT_RDGENERAL_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_RDGENERAL_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_RDGENERAL_EXPORT end definitions

// RDKIT_RDGEOMETRYLIB_EXPORT definitions
#ifdef RDKIT_RDGEOMETRYLIB_BUILD
#define RDKIT_RDGEOMETRYLIB_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_RDGEOMETRYLIB_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_RDGEOMETRYLIB_EXPORT end definitions

// RDKIT_RDINCHILIB_EXPORT definitions
#ifdef RDKIT_RDINCHILIB_BUILD
#define RDKIT_RDINCHILIB_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_RDINCHILIB_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_RDINCHILIB_EXPORT end definitions

// RDKIT_RDSTREAMS_EXPORT definitions
#ifdef RDKIT_RDSTREAMS_BUILD
#define RDKIT_RDSTREAMS_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_RDSTREAMS_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_RDSTREAMS_EXPORT end definitions

// RDKIT_RGROUPDECOMPOSITION_EXPORT definitions
#ifdef RDKIT_RGROUPDECOMPOSITION_BUILD
#define RDKIT_RGROUPDECOMPOSITION_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_RGROUPDECOMPOSITION_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_RGROUPDECOMPOSITION_EXPORT end definitions

// RDKIT_REDUCEDGRAPHS_EXPORT definitions
#ifdef RDKIT_REDUCEDGRAPHS_BUILD
#define RDKIT_REDUCEDGRAPHS_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_REDUCEDGRAPHS_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_REDUCEDGRAPHS_EXPORT end definitions

// RDKIT_RINGDECOMPOSERLIB_EXPORT definitions
#ifdef RDKIT_RINGDECOMPOSERLIB_BUILD
#define RDKIT_RINGDECOMPOSERLIB_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_RINGDECOMPOSERLIB_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_RINGDECOMPOSERLIB_EXPORT end definitions

// RDKIT_SLNPARSE_EXPORT definitions
#ifdef RDKIT_SLNPARSE_BUILD
#define RDKIT_SLNPARSE_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_SLNPARSE_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_SLNPARSE_EXPORT end definitions

// RDKIT_SCAFFOLDNETWORK_EXPORT definitions
#ifdef RDKIT_SCAFFOLDNETWORK_BUILD
#define RDKIT_SCAFFOLDNETWORK_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_SCAFFOLDNETWORK_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_SCAFFOLDNETWORK_EXPORT end definitions

// RDKIT_SHAPEHELPERS_EXPORT definitions
#ifdef RDKIT_SHAPEHELPERS_BUILD
#define RDKIT_SHAPEHELPERS_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_SHAPEHELPERS_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_SHAPEHELPERS_EXPORT end definitions

// RDKIT_SIMDIVPICKERS_EXPORT definitions
#ifdef RDKIT_SIMDIVPICKERS_BUILD
#define RDKIT_SIMDIVPICKERS_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_SIMDIVPICKERS_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_SIMDIVPICKERS_EXPORT end definitions

// RDKIT_SMILESPARSE_EXPORT definitions
#ifdef RDKIT_SMILESPARSE_BUILD
#define RDKIT_SMILESPARSE_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_SMILESPARSE_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_SMILESPARSE_EXPORT end definitions

// RDKIT_STRUCTCHECKER_EXPORT definitions
#ifdef RDKIT_STRUCTCHECKER_BUILD
#define RDKIT_STRUCTCHECKER_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_STRUCTCHECKER_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_STRUCTCHECKER_EXPORT end definitions

// RDKIT_SUBGRAPHS_EXPORT definitions
#ifdef RDKIT_SUBGRAPHS_BUILD
#define RDKIT_SUBGRAPHS_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_SUBGRAPHS_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_SUBGRAPHS_EXPORT end definitions

// RDKIT_SUBSTRUCTLIBRARY_EXPORT definitions
#ifdef RDKIT_SUBSTRUCTLIBRARY_BUILD
#define RDKIT_SUBSTRUCTLIBRARY_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_SUBSTRUCTLIBRARY_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_SUBSTRUCTLIBRARY_EXPORT end definitions

// RDKIT_SUBSTRUCTMATCH_EXPORT definitions
#ifdef RDKIT_SUBSTRUCTMATCH_BUILD
#define RDKIT_SUBSTRUCTMATCH_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_SUBSTRUCTMATCH_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_SUBSTRUCTMATCH_EXPORT end definitions

// RDKIT_TAUTOMERQUERY_EXPORT definitions
#ifdef RDKIT_TAUTOMERQUERY_BUILD
#define RDKIT_TAUTOMERQUERY_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_TAUTOMERQUERY_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_TAUTOMERQUERY_EXPORT end definitions

// RDKIT_TRAJECTORY_EXPORT definitions
#ifdef RDKIT_TRAJECTORY_BUILD
#define RDKIT_TRAJECTORY_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_TRAJECTORY_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_TRAJECTORY_EXPORT end definitions

// RDKIT_AVALON_CLIB_EXPORT definitions
#ifdef RDKIT_AVALON_CLIB_BUILD
#define RDKIT_AVALON_CLIB_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_AVALON_CLIB_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_AVALON_CLIB_EXPORT end definitions

// RDKIT_COORDGEN_EXPORT definitions
#ifdef RDKIT_COORDGEN_BUILD
#define RDKIT_COORDGEN_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_COORDGEN_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_COORDGEN_EXPORT end definitions

// RDKIT_FREESASA_CLIB_EXPORT definitions
#ifdef RDKIT_FREESASA_CLIB_BUILD
#define RDKIT_FREESASA_CLIB_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_FREESASA_CLIB_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_FREESASA_CLIB_EXPORT end definitions

// RDKIT_GA_EXPORT definitions
#ifdef RDKIT_GA_BUILD
#define RDKIT_GA_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_GA_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_GA_EXPORT end definitions

// RDKIT_HC_EXPORT definitions
#ifdef RDKIT_HC_BUILD
#define RDKIT_HC_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_HC_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_HC_EXPORT end definitions

// RDKIT_MAEPARSER_EXPORT definitions
#ifdef RDKIT_MAEPARSER_BUILD
#define RDKIT_MAEPARSER_EXPORT RDKIT_EXPORT_API
#else
#define RDKIT_MAEPARSER_EXPORT RDKIT_IMPORT_API
#endif
// RDKIT_MAEPARSER_EXPORT end definitions

/*
 * Do not dll export/import to export queries (it will mess up with the
 * templates), but make sure it is visible for *nix
 */
// RDKIT_QUERY_EXPORT definitions
#if defined(RDKIT_DYN_LINK) && defined(WIN32) && defined(BOOST_HAS_DECLSPEC)
#define RDKIT_QUERY_EXPORT
#else
#define RDKIT_QUERY_EXPORT RDKIT_GRAPHMOL_EXPORT
#endif
// RDKIT_QUERY_EXPORT end definitions
