# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.19)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget RDKit::rdkit_base RDKit::rdkit_py_base RDKit::Inchi RDKit::RDInchiLib RDKit::avalon_clib RDKit::AvalonLib RDKit::freesasa_clib RDKit::FreeSASALib RDKit::maeparser RDKit::coordgen RDKit::EHTLib RDKit::RingDecomposerLib RDKit::ga RDKit::RDGeneral RDKit::RDBoost RDKit::RDStreams RDKit::DataStructs RDKit::RDGeometryLib RDKit::Alignment RDKit::EigenSolvers RDKit::Optimizer RDKit::ForceField RDKit::DistGeometry RDKit::Catalogs RDKit::GraphMol RDKit::Depictor RDKit::SmilesParse RDKit::FileParsers RDKit::SubstructMatch RDKit::ChemReactions RDKit::ChemTransforms RDKit::TautomerQuery RDKit::Subgraphs RDKit::FilterCatalog RDKit::FragCatalog RDKit::Descriptors RDKit::Fingerprints RDKit::PartialCharges RDKit::MolTransforms RDKit::ForceFieldHelpers RDKit::DistGeomHelpers RDKit::MolAlign RDKit::O3AAlign RDKit::MolChemicalFeatures RDKit::ShapeHelpers RDKit::MolCatalog RDKit::MolDraw2D RDKit::FMCS RDKit::MolHash RDKit::MMPA RDKit::CIPLabeler RDKit::Deprotect RDKit::ReducedGraphs RDKit::Trajectory RDKit::SubstructLibrary RDKit::RGroupDecomposition RDKit::MolInterchange RDKit::MolStandardize RDKit::ScaffoldNetwork RDKit::MolEnumerator RDKit::Abbreviations RDKit::SimDivPickers RDKit::hc RDKit::InfoTheory RDKit::ChemicalFeatures)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target RDKit::rdkit_base
add_library(RDKit::rdkit_base INTERFACE IMPORTED)

set_target_properties(RDKit::rdkit_base PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "RDK_64BIT_BUILD;RDK_BUILD_DESCRIPTORS3D;RDK_HAS_EIGEN3;RDK_THREADSAFE_SSS;RDK_TEST_MULTITHREADED;RDK_USE_BOOST_SERIALIZATION;BOOST_SERIALIZATION_DYN_LINK;RDK_USE_STRICT_ROTOR_DEFINITION"
  INTERFACE_INCLUDE_DIRECTORIES "/Users/sergivela/Documents/Programes/cell2mol/env/include/python3.9;/Users/sergivela/Documents/Programes/cell2mol/env/lib/python3.9/site-packages/numpy/core/include;${_IMPORT_PREFIX}/include/rdkit;/Users/sergivela/Documents/Programes/cell2mol/env/include"
  INTERFACE_LINK_LIBRARIES "Eigen3::Eigen;Threads::Threads"
)

# Create imported target RDKit::rdkit_py_base
add_library(RDKit::rdkit_py_base INTERFACE IMPORTED)

set_target_properties(RDKit::rdkit_py_base PROPERTIES
  INTERFACE_LINK_LIBRARIES "Boost::python39"
)

# Create imported target RDKit::Inchi
add_library(RDKit::Inchi SHARED IMPORTED)

set_target_properties(RDKit::Inchi PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base"
)

# Create imported target RDKit::RDInchiLib
add_library(RDKit::RDInchiLib SHARED IMPORTED)

set_target_properties(RDKit::RDInchiLib PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::Inchi;RDKit::GraphMol;RDKit::RDGeneral;RDKit::Depictor;RDKit::SubstructMatch;RDKit::SmilesParse"
)

# Create imported target RDKit::avalon_clib
add_library(RDKit::avalon_clib SHARED IMPORTED)

set_target_properties(RDKit::avalon_clib PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base"
)

# Create imported target RDKit::AvalonLib
add_library(RDKit::AvalonLib SHARED IMPORTED)

set_target_properties(RDKit::AvalonLib PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::avalon_clib;RDKit::SubstructMatch;RDKit::FileParsers;RDKit::SmilesParse;RDKit::GraphMol;RDKit::DataStructs"
)

# Create imported target RDKit::freesasa_clib
add_library(RDKit::freesasa_clib SHARED IMPORTED)

set_target_properties(RDKit::freesasa_clib PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base"
)

# Create imported target RDKit::FreeSASALib
add_library(RDKit::FreeSASALib SHARED IMPORTED)

set_target_properties(RDKit::FreeSASALib PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::freesasa_clib;RDKit::GraphMol"
)

# Create imported target RDKit::maeparser
add_library(RDKit::maeparser SHARED IMPORTED)

set_target_properties(RDKit::maeparser PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;/Users/sergivela/Documents/Programes/cell2mol/env/lib/libboost_system.dylib;/Users/sergivela/Documents/Programes/cell2mol/env/lib/libboost_iostreams.dylib;/Users/sergivela/Documents/Programes/cell2mol/env/lib/libboost_regex.dylib"
)

# Create imported target RDKit::coordgen
add_library(RDKit::coordgen SHARED IMPORTED)

set_target_properties(RDKit::coordgen PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base"
)

# Create imported target RDKit::EHTLib
add_library(RDKit::EHTLib SHARED IMPORTED)

set_target_properties(RDKit::EHTLib PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;yaehmop_eht;RDKit::GraphMol"
)

# Create imported target RDKit::RingDecomposerLib
add_library(RDKit::RingDecomposerLib SHARED IMPORTED)

set_target_properties(RDKit::RingDecomposerLib PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base"
)

# Create imported target RDKit::ga
add_library(RDKit::ga SHARED IMPORTED)

set_target_properties(RDKit::ga PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base"
)

# Create imported target RDKit::RDGeneral
add_library(RDKit::RDGeneral SHARED IMPORTED)

set_target_properties(RDKit::RDGeneral PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;Threads::Threads"
)

# Create imported target RDKit::RDBoost
add_library(RDKit::RDBoost SHARED IMPORTED)

set_target_properties(RDKit::RDBoost PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::RDGeneral;RDKit::rdkit_base"
)

# Create imported target RDKit::RDStreams
add_library(RDKit::RDStreams SHARED IMPORTED)

set_target_properties(RDKit::RDStreams PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;Boost::iostreams"
)

# Create imported target RDKit::DataStructs
add_library(RDKit::DataStructs SHARED IMPORTED)

set_target_properties(RDKit::DataStructs PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::RDGeneral"
)

# Create imported target RDKit::RDGeometryLib
add_library(RDKit::RDGeometryLib SHARED IMPORTED)

set_target_properties(RDKit::RDGeometryLib PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::DataStructs;RDKit::RDGeneral"
)

# Create imported target RDKit::Alignment
add_library(RDKit::Alignment SHARED IMPORTED)

set_target_properties(RDKit::Alignment PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::RDGeometryLib"
)

# Create imported target RDKit::EigenSolvers
add_library(RDKit::EigenSolvers SHARED IMPORTED)

set_target_properties(RDKit::EigenSolvers PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::RDGeneral"
)

# Create imported target RDKit::Optimizer
add_library(RDKit::Optimizer SHARED IMPORTED)

set_target_properties(RDKit::Optimizer PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::RDGeometryLib;RDKit::Trajectory;RDKit::RDGeneral"
)

# Create imported target RDKit::ForceField
add_library(RDKit::ForceField SHARED IMPORTED)

set_target_properties(RDKit::ForceField PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::Optimizer;RDKit::Trajectory"
)

# Create imported target RDKit::DistGeometry
add_library(RDKit::DistGeometry SHARED IMPORTED)

set_target_properties(RDKit::DistGeometry PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::EigenSolvers;RDKit::ForceField;RDKit::ForceFieldHelpers"
)

# Create imported target RDKit::Catalogs
add_library(RDKit::Catalogs SHARED IMPORTED)

set_target_properties(RDKit::Catalogs PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::RDGeneral"
)

# Create imported target RDKit::GraphMol
add_library(RDKit::GraphMol SHARED IMPORTED)

set_target_properties(RDKit::GraphMol PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::RDGeometryLib;RDKit::RDGeneral;RDKit::RingDecomposerLib"
)

# Create imported target RDKit::Depictor
add_library(RDKit::Depictor SHARED IMPORTED)

set_target_properties(RDKit::Depictor PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::MolAlign;RDKit::coordgen;RDKit::maeparser;/Users/sergivela/Documents/Programes/cell2mol/env/lib/libboost_system.dylib;/Users/sergivela/Documents/Programes/cell2mol/env/lib/libboost_iostreams.dylib;/Users/sergivela/Documents/Programes/cell2mol/env/lib/libboost_regex.dylib;/Users/sergivela/Documents/Programes/cell2mol/env/lib/libboost_system.dylib;/Users/sergivela/Documents/Programes/cell2mol/env/lib/libboost_iostreams.dylib;/Users/sergivela/Documents/Programes/cell2mol/env/lib/libboost_regex.dylib;RDKit::SubstructMatch;RDKit::GraphMol;RDKit::RDGeneral"
)

# Create imported target RDKit::SmilesParse
add_library(RDKit::SmilesParse SHARED IMPORTED)

set_target_properties(RDKit::SmilesParse PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::GraphMol;RDKit::RDGeneral"
)

# Create imported target RDKit::FileParsers
add_library(RDKit::FileParsers SHARED IMPORTED)

set_target_properties(RDKit::FileParsers PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::Depictor;RDKit::SmilesParse;RDKit::GraphMol;RDKit::maeparser;/Users/sergivela/Documents/Programes/cell2mol/env/lib/libboost_system.dylib;/Users/sergivela/Documents/Programes/cell2mol/env/lib/libboost_iostreams.dylib;/Users/sergivela/Documents/Programes/cell2mol/env/lib/libboost_regex.dylib;/Users/sergivela/Documents/Programes/cell2mol/env/lib/libboost_system.dylib;/Users/sergivela/Documents/Programes/cell2mol/env/lib/libboost_iostreams.dylib;/Users/sergivela/Documents/Programes/cell2mol/env/lib/libboost_regex.dylib;/Users/sergivela/Documents/Programes/cell2mol/env/lib/libz.dylib"
)

# Create imported target RDKit::SubstructMatch
add_library(RDKit::SubstructMatch SHARED IMPORTED)

set_target_properties(RDKit::SubstructMatch PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::GraphMol;RDKit::RDGeneral"
)

# Create imported target RDKit::ChemReactions
add_library(RDKit::ChemReactions SHARED IMPORTED)

set_target_properties(RDKit::ChemReactions PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::FilterCatalog;RDKit::Descriptors;RDKit::Fingerprints;RDKit::DataStructs;RDKit::Depictor;RDKit::FileParsers;RDKit::SubstructMatch;RDKit::ChemTransforms;RDKit::GraphMol;/Users/sergivela/Documents/Programes/cell2mol/env/lib/libboost_serialization.dylib"
)

# Create imported target RDKit::ChemTransforms
add_library(RDKit::ChemTransforms SHARED IMPORTED)

set_target_properties(RDKit::ChemTransforms PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::GraphMol;RDKit::SubstructMatch;RDKit::SmilesParse"
)

# Create imported target RDKit::TautomerQuery
add_library(RDKit::TautomerQuery SHARED IMPORTED)

set_target_properties(RDKit::TautomerQuery PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::GraphMol;RDKit::RDGeneral;RDKit::MolStandardize"
)

# Create imported target RDKit::Subgraphs
add_library(RDKit::Subgraphs SHARED IMPORTED)

set_target_properties(RDKit::Subgraphs PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::GraphMol;RDKit::RDGeneral"
)

# Create imported target RDKit::FilterCatalog
add_library(RDKit::FilterCatalog SHARED IMPORTED)

set_target_properties(RDKit::FilterCatalog PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::Subgraphs;RDKit::SubstructMatch;RDKit::SmilesParse;RDKit::GraphMol;RDKit::Catalogs;/Users/sergivela/Documents/Programes/cell2mol/env/lib/libboost_serialization.dylib"
)

# Create imported target RDKit::FragCatalog
add_library(RDKit::FragCatalog SHARED IMPORTED)

set_target_properties(RDKit::FragCatalog PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::Subgraphs;RDKit::SubstructMatch;RDKit::SmilesParse;RDKit::Catalogs;RDKit::GraphMol;RDKit::RDGeneral"
)

# Create imported target RDKit::Descriptors
add_library(RDKit::Descriptors SHARED IMPORTED)

set_target_properties(RDKit::Descriptors PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::PartialCharges;RDKit::SmilesParse;RDKit::FileParsers;RDKit::Subgraphs;RDKit::SubstructMatch;RDKit::MolTransforms;RDKit::GraphMol;RDKit::EigenSolvers;RDKit::RDGeneral"
)

# Create imported target RDKit::Fingerprints
add_library(RDKit::Fingerprints SHARED IMPORTED)

set_target_properties(RDKit::Fingerprints PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::DataStructs;RDKit::Subgraphs;RDKit::SubstructMatch;RDKit::SmilesParse;RDKit::GraphMol;RDKit::RDGeneral"
)

# Create imported target RDKit::PartialCharges
add_library(RDKit::PartialCharges SHARED IMPORTED)

set_target_properties(RDKit::PartialCharges PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::GraphMol;RDKit::RDGeneral"
)

# Create imported target RDKit::MolTransforms
add_library(RDKit::MolTransforms SHARED IMPORTED)

set_target_properties(RDKit::MolTransforms PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::GraphMol;RDKit::EigenSolvers;RDKit::RDGeneral"
)

# Create imported target RDKit::ForceFieldHelpers
add_library(RDKit::ForceFieldHelpers SHARED IMPORTED)

set_target_properties(RDKit::ForceFieldHelpers PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::SmilesParse;RDKit::SubstructMatch;RDKit::ForceField"
)

# Create imported target RDKit::DistGeomHelpers
add_library(RDKit::DistGeomHelpers SHARED IMPORTED)

set_target_properties(RDKit::DistGeomHelpers PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::ForceFieldHelpers;RDKit::SubstructMatch;RDKit::GraphMol;RDKit::DistGeometry;RDKit::Alignment"
)

# Create imported target RDKit::MolAlign
add_library(RDKit::MolAlign SHARED IMPORTED)

set_target_properties(RDKit::MolAlign PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::MolTransforms;RDKit::SubstructMatch;RDKit::Alignment;RDKit::GraphMol;RDKit::RDGeneral"
)

# Create imported target RDKit::O3AAlign
add_library(RDKit::O3AAlign SHARED IMPORTED)

set_target_properties(RDKit::O3AAlign PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::MolAlign;RDKit::MolTransforms;RDKit::SubstructMatch;RDKit::Alignment;RDKit::GraphMol;RDKit::RDGeneral;RDKit::ForceFieldHelpers"
)

# Create imported target RDKit::MolChemicalFeatures
add_library(RDKit::MolChemicalFeatures SHARED IMPORTED)

set_target_properties(RDKit::MolChemicalFeatures PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::SubstructMatch;RDKit::SmilesParse;RDKit::GraphMol"
)

# Create imported target RDKit::ShapeHelpers
add_library(RDKit::ShapeHelpers SHARED IMPORTED)

set_target_properties(RDKit::ShapeHelpers PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::MolTransforms;RDKit::GraphMol;RDKit::RDGeneral"
)

# Create imported target RDKit::MolCatalog
add_library(RDKit::MolCatalog SHARED IMPORTED)

set_target_properties(RDKit::MolCatalog PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::GraphMol;RDKit::Catalogs"
)

# Create imported target RDKit::MolDraw2D
add_library(RDKit::MolDraw2D SHARED IMPORTED)

set_target_properties(RDKit::MolDraw2D PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "RDK_BUILD_CAIRO_SUPPORT;RDK_BUILD_FREETYPE_SUPPORT"
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::ChemReactions;RDKit::Depictor;RDKit::MolTransforms;RDKit::SubstructMatch;RDKit::Subgraphs;RDKit::GraphMol;RDKit::EigenSolvers;Cairo::Cairo;Freetype::Freetype"
)

# Create imported target RDKit::FMCS
add_library(RDKit::FMCS SHARED IMPORTED)

set_target_properties(RDKit::FMCS PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::Depictor;RDKit::SmilesParse;RDKit::FileParsers;RDKit::ChemTransforms;RDKit::SubstructMatch;RDKit::GraphMol"
)

# Create imported target RDKit::MolHash
add_library(RDKit::MolHash SHARED IMPORTED)

set_target_properties(RDKit::MolHash PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::Depictor;RDKit::Descriptors;RDKit::GraphMol"
)

# Create imported target RDKit::MMPA
add_library(RDKit::MMPA SHARED IMPORTED)

set_target_properties(RDKit::MMPA PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::SubstructMatch;RDKit::Depictor;RDKit::FileParsers;RDKit::ChemTransforms;RDKit::GraphMol;RDKit::RDGeneral"
)

# Create imported target RDKit::CIPLabeler
add_library(RDKit::CIPLabeler SHARED IMPORTED)

set_target_properties(RDKit::CIPLabeler PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::GraphMol"
)

# Create imported target RDKit::Deprotect
add_library(RDKit::Deprotect SHARED IMPORTED)

set_target_properties(RDKit::Deprotect PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::ChemReactions;RDKit::FilterCatalog;RDKit::Descriptors;RDKit::Fingerprints;RDKit::DataStructs;RDKit::Depictor;RDKit::FileParsers;RDKit::SubstructMatch;RDKit::ChemTransforms;RDKit::GraphMol"
)

# Create imported target RDKit::ReducedGraphs
add_library(RDKit::ReducedGraphs SHARED IMPORTED)

set_target_properties(RDKit::ReducedGraphs PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::SubstructMatch;RDKit::SmilesParse;RDKit::GraphMol;RDKit::RDGeneral"
)

# Create imported target RDKit::Trajectory
add_library(RDKit::Trajectory SHARED IMPORTED)

set_target_properties(RDKit::Trajectory PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::GraphMol;RDKit::RDGeneral"
)

# Create imported target RDKit::SubstructLibrary
add_library(RDKit::SubstructLibrary SHARED IMPORTED)

set_target_properties(RDKit::SubstructLibrary PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::TautomerQuery;RDKit::MolStandardize;RDKit::Fingerprints;RDKit::SubstructMatch;RDKit::SmilesParse;RDKit::GraphMol;RDKit::Catalogs;RDKit::DataStructs;RDKit::RDGeneral;/Users/sergivela/Documents/Programes/cell2mol/env/lib/libboost_serialization.dylib"
)

# Create imported target RDKit::RGroupDecomposition
add_library(RDKit::RGroupDecomposition SHARED IMPORTED)

set_target_properties(RDKit::RGroupDecomposition PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::FMCS;RDKit::ChemTransforms;RDKit::SubstructMatch;RDKit::SmilesParse;RDKit::Fingerprints;RDKit::GraphMol;RDKit::RDGeneral;RDKit::ga"
)

# Create imported target RDKit::MolInterchange
add_library(RDKit::MolInterchange SHARED IMPORTED)

set_target_properties(RDKit::MolInterchange PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::GraphMol"
)

# Create imported target RDKit::MolStandardize
add_library(RDKit::MolStandardize SHARED IMPORTED)

set_target_properties(RDKit::MolStandardize PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::ChemReactions;RDKit::ChemTransforms;RDKit::SmilesParse;RDKit::SubstructMatch;RDKit::Descriptors;RDKit::GraphMol"
)

# Create imported target RDKit::ScaffoldNetwork
add_library(RDKit::ScaffoldNetwork SHARED IMPORTED)

set_target_properties(RDKit::ScaffoldNetwork PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::MolStandardize;RDKit::ChemReactions;RDKit::ChemTransforms;RDKit::SmilesParse;RDKit::SubstructMatch;RDKit::GraphMol;RDKit::RDGeneral"
)

# Create imported target RDKit::MolEnumerator
add_library(RDKit::MolEnumerator SHARED IMPORTED)

set_target_properties(RDKit::MolEnumerator PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::FileParsers;RDKit::ChemReactions;RDKit::ChemTransforms;RDKit::SubstructMatch;RDKit::GraphMol;RDKit::RDGeneral"
)

# Create imported target RDKit::Abbreviations
add_library(RDKit::Abbreviations SHARED IMPORTED)

set_target_properties(RDKit::Abbreviations PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::SmilesParse;RDKit::SubstructMatch;RDKit::GraphMol;RDKit::RDGeneral"
)

# Create imported target RDKit::SimDivPickers
add_library(RDKit::SimDivPickers SHARED IMPORTED)

set_target_properties(RDKit::SimDivPickers PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::hc;RDKit::RDGeneral"
)

# Create imported target RDKit::hc
add_library(RDKit::hc SHARED IMPORTED)

set_target_properties(RDKit::hc PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base"
)

# Create imported target RDKit::InfoTheory
add_library(RDKit::InfoTheory SHARED IMPORTED)

set_target_properties(RDKit::InfoTheory PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::DataStructs;RDKit::RDGeneral"
)

# Create imported target RDKit::ChemicalFeatures
add_library(RDKit::ChemicalFeatures SHARED IMPORTED)

set_target_properties(RDKit::ChemicalFeatures PROPERTIES
  INTERFACE_LINK_LIBRARIES "RDKit::rdkit_base;RDKit::RDGeneral;RDKit::RDGeometryLib"
)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/rdkit-targets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
